<img src="Logo.png" width="100" align="left"/> 

# <center> Unit 3 Project </center>
#  <center> Third section : supervised task </center>

In this notebook you will be building and training a supervised learning model to classify your data.

For this task we will be using another classification model "The random forests" model.

Steps for this task: 
1. Load the already clustered dataset 
2. Take into consideration that in this task we will not be using the already added column "Cluster" 
3. Split your data.
3. Build your model using the SKlearn RandomForestClassifier class 
4. classify your data and test the performance of your model 
5. Evaluate the model ( accepted models should have at least an accuracy of 86%). Play with hyper parameters and provide a report about that.
6. Provide evidence on the quality of your model (not overfitted good metrics)
7. Create a new test dataset that contains the testset + an additional column called "predicted_class" stating the class predicted by your random forest classifier for each data point of the test set.

## 1. Load the data and split the data:

In [1]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd 
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
# To-Do:  load the data 
df = pd.read_csv("clustered_HepatitisC.csv")
df.head()

,ID,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,cluster
0,1,0,32,1,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0,3
1,2,0,32,1,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5,3
2,3,0,32,1,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3,3
3,4,0,32,1,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7,3
4,5,0,32,1,39.2,74.1,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7,3

In [3]:
# To-Do : keep only the columns to be used : all features except ID, cluster 
cols=list(df.columns)
cols.remove('cluster')
cols.remove('ID')

# The target here is the Category column 
# Do not forget to split your data (this is a classification task)
# test set size should be 20% of the data 
cols.remove('Category')
X=df[cols]
y=df['Category']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)

## 2. Building the model and training and evaluate the performance:

In [4]:
# To-do build the model and train it 
# note that you will be providing explanation about the hyper parameter tuning 
# So you will be iterating a number of times before getting the desired performance 
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)

RandomForestClassifier()

In [5]:
y_hat = clf.predict(X_train)
y_tst=clf.predict(X_test)

In [6]:
# To-do : evaluate the model in terms of accuracy and precision 
from sklearn.metrics import precision_score, accuracy_score
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

# Provide evidence that your model is not overfitting 
print("Accuracy for training data:",accuracy_score(y_train, y_hat))
print("Accuracy for testing data:",accuracy_score(y_test, y_tst))
print("the Accuracy for testing data is well so we are goood fitting")


#Create a Gaussian Classifier
kernel = 1.0 * RBF(1.0)
gpc = GaussianProcessClassifier(kernel=kernel,random_state=0).fit(X_train, y_train)
gpc.score(X_train, y_train)
res=gpc.predict_proba(X_test)
print(res)
#Train the model using the training sets y_pred=clf.predict(X_test)
y_pred = clf.predict(X_test)
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy for training data: 1.0
Accuracy for testing data: 0.9349593495934959
the Accuracy for testing data is well so we are goood fitting
[[9.69046637e-01 1.66261256e-02 3.83155060e-03 2.59223216e-03
  7.90345428e-03]
 [6.35054564e-01 1.60702279e-01 1.21270881e-02 7.32686954e-02
  1.18847373e-01]
 [9.78459175e-01 4.84081870e-03 2.83165098e-03 1.20724055e-02
  1.79595016e-03]
 [9.63958833e-01 1.25234484e-02 6.30470928e-04 1.37315476e-02
  9.15570038e-03]
 [9.66149822e-01 1.20967553e-02 3.67514241e-03 9.53643008e-03
  8.54184980e-03]
 [2.06774331e-01 2.23194243e-01 1.21434539e-01 1.10905220e-01
  3.37691666e-01]
 [9.62762891e-01 6.37312422e-03 1.45039707e-02 1.22375470e-02
  4.12246668e-03]
 [9.60403651e-01 3.05213035e-02 2.97317447e-03 1.88452161e-03
  4.21734950e-03]
 [9.67711284e-01 1.57593248e-02 2.04158556e-03 1.05789282e-02
  3.90887725e-03]
 [8.79232743e-01 1.05652509e-01 4.98145663e-04 3.44668777e-03
  1.11699143e-02]
 [9.77616709e-01 7.71152161e-03 6.63074652e-03 6.91808623e-03
  1.12293635e-03]
 [9.72699264e-01 1.82600460e-02 5.45135660e-03 1.95144615e-03
  1.63788767e-03]
 [9.55469585e-01 2.12848326e-02 6.90119544e-03 1.09239868e-02
  5.42040022e-03]
 [5.20553176e-01 1.30428954e-01 1.09461723e-02 7.71577788e-02
  2.60913918e-01]
 [9.39178212e-01 1.09766962e-02 2.87028899e-04 3.71060543e-02
  1.24520082e-02]
 [9.57358593e-01 9.17686301e-03 4.97390415e-03 2.46698272e-02
  3.82081240e-03]
 [9.57601382e-01 1.13111348e-02 1.04807580e-02 1.62978079e-02
  4.30891759e-03]
 [8.78281926e-01 9.06202585e-02 7.04673050e-03 4.56014836e-03
  1.94909363e-02]
 [9.79324365e-01 3.88744918e-03 1.26260199e-03 1.37133747e-02
  1.81220876e-03]
 [9.71905353e-01 1.21351800e-02 9.91906820e-04 9.71878532e-03
  5.24877492e-03]
 [2.01151995e-01 2.00898036e-01 2.00343049e-01 1.95792429e-01
  2.01814491e-01]
 [8.98682361e-01 8.76582875e-02 5.43147975e-04 5.22824268e-04
  1.25933793e-02]
 [9.69004146e-01 5.04779393e-03 9.73687617e-03 1.41560257e-02
  2.05515790e-03]
 [2.74428492e-01 1.55285871e-01 3.74843489e-02 1.58495405e-01
  3.74305884e-01]
 [9.80632322e-01 8.69670412e-03 3.66758921e-03 5.24334743e-03
  1.76003677e-03]
 [9.55532406e-01 1.37135246e-02 1.90108905e-04 2.14501836e-02
  9.11377728e-03]
 [9.33791593e-01 6.40297411e-03 4.94534996e-02 8.99766594e-03
  1.35426752e-03]
 [9.35521999e-01 9.80312266e-03 4.39146328e-02 9.23309159e-03
  1.52715416e-03]
 [9.01242258e-01 2.54869958e-02 2.95245830e-03 5.06220041e-02
  1.96962843e-02]
 [9.73961612e-01 6.48599623e-03 2.65984492e-03 1.39125267e-02
  2.98002054e-03]
 [9.80469836e-01 9.84396421e-03 1.13406544e-03 6.76056323e-03
  1.79157118e-03]
 [9.51185092e-01 4.12025662e-02 2.16650313e-05 8.15924719e-04
  6.77475229e-03]
 [9.81547867e-01 9.67727798e-03 7.07298058e-04 5.56550040e-03
  2.50205606e-03]
 [9.62984305e-01 2.07246692e-02 7.04375293e-03 2.59916961e-03
  6.64810329e-03]
 [9.67443424e-01 5.38467880e-03 1.09354128e-02 1.31823844e-02
  3.05410045e-03]
 [9.74913674e-01 1.43463187e-02 6.56316669e-03 1.64944188e-03
  2.52739846e-03]
 [9.45168041e-01 3.54362501e-02 3.57860265e-03 4.42034326e-03
  1.13967627e-02]
 [2.02532270e-01 8.58027368e-02 5.29791841e-02 1.16609364e-01
  5.42076446e-01]
 [2.79054082e-01 3.00914089e-01 8.32378281e-02 6.56992925e-02
  2.71094708e-01]
 [8.22535569e-01 1.42456414e-02 1.39069236e-01 1.73357919e-02
  6.81376157e-03]
 [9.74455869e-01 1.10562350e-02 6.83939219e-03 4.89735404e-03
  2.75114963e-03]
 [9.33429736e-01 5.18250073e-03 5.20642886e-02 8.21764445e-03
  1.10583049e-03]
 [9.79585624e-01 1.31682609e-02 6.59674656e-04 3.14514258e-03
  3.44129746e-03]
 [1.59309795e-01 2.00013253e-01 1.58931564e-01 6.58605251e-02
  4.15884864e-01]
 [9.75579334e-01 1.34854833e-02 4.88278410e-03 1.86798146e-03
  4.18441745e-03]
 [9.63447961e-01 1.75572623e-02 5.47716870e-03 5.67360835e-03
  7.84399975e-03]
 [9.83096554e-01 6.28344014e-03 1.62946117e-03 7.03901327e-03
  1.95153128e-03]
 [8.30726434e-01 1.88752134e-02 1.37737921e-01 8.86224771e-03
  3.79818435e-03]
 [9.81422314e-01 1.13253200e-02 4.49737475e-04 3.78016722e-03
  3.02246115e-03]
 [9.38433289e-01 3.43275900e-02 2.11342098e-02 3.20058065e-03
  2.90433019e-03]
 [9.30981590e-01 1.84557468e-02 9.55884355e-03 2.36845880e-02
  1.73192321e-02]
 [9.64864154e-01 2.61071070e-02 6.09791652e-03 1.22319967e-03
  1.70762272e-03]
 [9.05036865e-01 8.12120759e-02 9.94773981e-05 1.66709782e-03
  1.19844837e-02]
 [9.49514310e-01 2.25968079e-02 2.30754542e-02 2.58908485e-03
  2.22434345e-03]
 [7.17591640e-01 1.08305631e-02 2.03456813e-01 6.16573239e-02
  6.46366035e-03]
 [9.66691846e-01 6.42294915e-03 8.89641920e-04 1.51849028e-02
  1.08106597e-02]
 [9.84969111e-01 4.63165321e-03 2.51186549e-03 6.07140256e-03
  1.81596818e-03]
 [9.53345534e-01 3.28705165e-02 1.02390785e-02 1.30042377e-03
  2.24444680e-03]
 [6.04514042e-02 1.48574510e-01 9.43262778e-02 4.70001057e-01
  2.26646751e-01]
 [7.61967327e-01 4.19888852e-03 2.01991233e-01 2.98381150e-02
  2.00443691e-03]
 [9.63436838e-01 1.30595912e-02 1.83422170e-02 2.89383445e-03
  2.26751959e-03]
 [9.75461620e-01 8.03950168e-03 8.11629903e-03 6.93910562e-03
  1.44347386e-03]
 [9.42501975e-01 8.56349714e-03 3.86178460e-02 7.93868871e-03
  2.37799283e-03]
 [8.49854576e-01 1.00587997e-02 1.24275488e-01 1.40268424e-02
  1.78429459e-03]
 [9.62371215e-01 1.33502599e-02 2.13280429e-02 1.85537757e-03
  1.09510459e-03]
 [9.71021085e-01 1.97620304e-02 2.49801650e-03 3.67841951e-03
  3.04044821e-03]
 [7.61478713e-02 2.00174646e-01 4.15186763e-03 2.33411564e-02
  6.96184458e-01]
 [9.69734168e-01 1.92941047e-02 7.40329374e-03 1.41787336e-03
  2.15056032e-03]
 [1.15439720e-01 5.17320868e-01 1.88820245e-02 1.37987889e-01
  2.10369498e-01]
 [6.60593908e-01 1.92094203e-02 3.00590700e-01 1.22016362e-02
  7.40433611e-03]
 [9.73119843e-01 1.00793436e-02 8.52366495e-03 5.74788334e-03
  2.52926563e-03]
 [6.89361227e-01 6.83763833e-02 1.75398421e-02 7.65892726e-02
  1.48133275e-01]
 [1.31981428e-01 1.65466711e-01 3.90295470e-02 3.13037073e-01
  3.50485240e-01]
 [9.78245780e-01 1.47893014e-02 4.42217123e-04 3.19793026e-03
  3.32477101e-03]
 [9.75424655e-01 8.58297148e-03 1.67483901e-03 1.22756329e-02
  2.04190201e-03]
 [6.00710016e-02 5.94278427e-02 3.01616581e-02 5.69810162e-01
  2.80529335e-01]
 [9.63841173e-01 9.13032354e-03 2.71000067e-03 2.11060189e-02
  3.21248393e-03]
 [8.64530071e-01 4.98386829e-02 4.42613914e-02 3.46403517e-03
  3.79058198e-02]
 [9.70883367e-01 7.29516816e-03 1.33759744e-02 7.17123266e-03
  1.27425820e-03]
 [9.39064819e-01 4.16131721e-02 1.64847940e-03 5.97674295e-03
  1.16967863e-02]
 [9.81912922e-01 9.27966866e-03 6.27050482e-04 4.65091728e-03
  3.52944161e-03]
 [9.23505543e-01 2.32131225e-02 2.09943793e-02 7.08735689e-03
  2.51995982e-02]
 [9.51990588e-01 7.94183079e-03 2.91834140e-02 8.63099474e-03
  2.25317246e-03]
 [8.12094141e-01 8.07090719e-02 2.21116924e-02 2.06639806e-02
  6.44211137e-02]
 [9.13272353e-01 3.80934729e-02 4.86338446e-04 5.00898342e-03
  4.31388525e-02]
 [9.78991435e-01 1.14601225e-02 2.79267539e-04 4.40422532e-03
  4.86494966e-03]
 [9.70939510e-01 2.43885958e-02 7.71490846e-04 1.42596905e-03
  2.47443468e-03]
 [9.54435597e-01 2.15302655e-02 1.85831238e-03 1.25771939e-02
  9.59863103e-03]
 [9.45589907e-01 1.55574267e-02 3.02173190e-02 4.27059651e-03
  4.36475039e-03]
 [4.02143236e-02 6.98888104e-02 9.54986840e-02 4.14451344e-01
  3.79946838e-01]
 [9.75791523e-01 1.30824407e-02 3.36387587e-04 6.28780655e-03
  4.50184179e-03]
 [9.56968822e-01 3.64908404e-02 3.80465060e-03 7.20502915e-04
  2.01518452e-03]
 [9.37000478e-01 3.08748822e-02 1.49549239e-02 1.11822007e-02
  5.98751544e-03]
 [9.70332115e-01 9.98408124e-03 1.19414922e-02 4.80912850e-03
  2.93318317e-03]
 [9.65226818e-01 1.81017683e-02 1.13244438e-02 3.14017059e-03
  2.20679929e-03]
 [9.57861958e-01 2.00110436e-02 1.40332894e-02 5.82252824e-03
  2.27118067e-03]
 [9.72756897e-01 1.00581175e-02 1.15053558e-02 3.33389975e-03
  2.34573006e-03]
 [9.78821162e-01 1.09644198e-02 4.96460274e-03 2.97397321e-03
  2.27584196e-03]
 [9.28809821e-01 4.90296653e-02 5.71738449e-03 3.66136545e-03
  1.27817642e-02]
 [9.78806027e-01 8.41561467e-03 6.88041829e-03 4.40567407e-03
  1.49226602e-03]
 [9.06377745e-01 6.91593992e-02 4.14661216e-04 2.49766123e-04
  2.37984288e-02]
 [9.71061735e-01 3.47008493e-03 9.19563653e-03 1.47806709e-02
  1.49187221e-03]
 [9.71998528e-01 1.01845324e-02 2.07661526e-03 1.31049302e-02
  2.63539416e-03]
 [9.79321384e-01 8.61805062e-03 7.37434245e-03 3.46759666e-03
  1.21862665e-03]
 [5.46986954e-01 8.96194494e-02 2.53847740e-04 8.90071366e-02
  2.74132612e-01]
 [4.14477546e-02 5.18008114e-02 1.43081846e-01 6.31314167e-01
  1.32355421e-01]
 [9.54757473e-01 9.51444399e-03 1.42951144e-02 1.70616442e-02
  4.37132437e-03]
 [1.80197161e-01 2.12942604e-01 1.52549102e-01 1.39525368e-01
  3.14785766e-01]
 [9.44539574e-01 2.26470340e-02 3.13148820e-04 1.48662536e-02
  1.76339891e-02]
 [4.99772747e-01 2.45767685e-02 2.10140449e-02 2.36126537e-01
  2.18509902e-01]
 [9.36837900e-01 1.34262967e-02 4.14121713e-02 5.69520944e-03
  2.62842274e-03]
 [9.80129092e-01 6.15687714e-03 5.82209775e-03 6.91059730e-03
  9.81335398e-04]
 [7.68400354e-01 8.62230636e-02 2.48868389e-02 1.11549610e-02
  1.09334782e-01]
 [7.86772690e-01 9.19743804e-03 1.94709412e-01 7.10315766e-03
  2.21730253e-03]
 [8.95486498e-01 1.95796743e-02 3.32524785e-04 3.98323763e-02
  4.47689262e-02]
 [9.66950631e-01 2.07649367e-02 2.12801599e-04 6.23293594e-03
  5.83869473e-03]
 [9.63874126e-01 1.80325394e-02 1.26490941e-02 3.08246754e-03
  2.36177250e-03]
 [9.56065785e-01 1.74794074e-02 1.57676219e-02 4.35620954e-03
  6.33097657e-03]
 [9.02636553e-01 1.17020028e-02 7.82266112e-02 4.98617689e-03
  2.44865596e-03]
 [9.56438105e-01 2.02795381e-02 8.93881479e-03 9.26032004e-03
  5.08322170e-03]
 [9.39052731e-01 3.87497369e-02 2.22828979e-03 1.08532838e-02
  9.11595892e-03]
 [5.80815235e-02 4.68266312e-02 6.89252498e-02 6.41525471e-01
  1.84641124e-01]
 [9.74156042e-01 9.83420543e-03 7.30999698e-04 1.15685479e-02
  3.71020537e-03]]
Accuracy: 0.9349593495934959

> Hint : A Perfect accuracy on the train set suggest that we have an overfitted model So the student should be able to provide a detailed table about the hyper parameters / parameters tuning with a good conclusion stating that the model has at least an accuracy of 86% on the test set without signs of overfitting

## 3. Create the summary test set with the additional predicted class column: 
In this part you need to add the predicted class as a column to your test dataframe and save this one

In [7]:
# To-Do : create the complete test dataframe : it should contain all the feature column + the actual target and the ID as well  
# test_df=X_train
test_df=df.loc[X_test.index]
test_df["Category"]=y_test
test_df.head()

,ID,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,cluster
49,50,0,36,1,47.8,89.0,48.5,38.4,8.6,8.26,5.62,96.0,21.9,76.2,3
496,497,0,56,0,45.1,79.1,39.0,30.5,5.2,6.47,5.10,64.0,145.3,66.7,4
211,212,0,51,1,45.9,66.7,31.8,28.1,9.0,10.08,5.61,85.0,36.2,73.0,3
249,250,0,55,1,44.7,71.6,22.9,22.1,5.5,6.82,4.61,105.0,59.2,72.7,4
142,143,0,45,1,43.2,68.2,27.8,42.3,6.6,10.93,6.61,105.0,27.2,74.5,3

In [8]:
test_df.head()

,ID,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,cluster
49,50,0,36,1,47.8,89.0,48.5,38.4,8.6,8.26,5.62,96.0,21.9,76.2,3
496,497,0,56,0,45.1,79.1,39.0,30.5,5.2,6.47,5.10,64.0,145.3,66.7,4
211,212,0,51,1,45.9,66.7,31.8,28.1,9.0,10.08,5.61,85.0,36.2,73.0,3
249,250,0,55,1,44.7,71.6,22.9,22.1,5.5,6.82,4.61,105.0,59.2,72.7,4
142,143,0,45,1,43.2,68.2,27.8,42.3,6.6,10.93,6.61,105.0,27.2,74.5,3

In [9]:
# To-Do : Add the predicted_class column 
test_df["Predicted_class"] = y_pred
test_df

,ID,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,cluster,Predicted_class
49,50,0,36,1,47.8,89.0,48.5,38.4,8.6,8.26,5.62,96.0,21.9,76.2,3,0
496,497,0,56,0,45.1,79.1,39.0,30.5,5.2,6.47,5.10,64.0,145.3,66.7,4,0
211,212,0,51,1,45.9,66.7,31.8,28.1,9.0,10.08,5.61,85.0,36.2,73.0,3,0
249,250,0,55,1,44.7,71.6,22.9,22.1,5.5,6.82,4.61,105.0,59.2,72.7,4,0
142,143,0,45,1,43.2,68.2,27.8,42.3,6.6,10.93,6.61,105.0,27.2,74.5,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,11,0,32,1,44.3,52.3,21.7,22.4,17.2,4.15,3.57,78.0,24.1,75.4,3,0
419,420,0,47,0,35.6,37.5,17.6,18.0,4.7,4.32,5.59,75.0,13.0,66.0,3,0
495,496,0,56,0,33.2,54.3,15.5,22.8,8.0,5.61,3.87,55.0,19.1,63.1,3,0
557,558,2,51,1,43.0,37.2,21.4,132.8,5.0,10.12,5.23,76.2,76.4,76.7,4,3
266,267,0,58,1,40.9,55.8,17.5,23.0,5.3,8.52,6.41,93.0,18.5,70.9,3,0

In [10]:
test_df.head()

,ID,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,cluster,Predicted_class
49,50,0,36,1,47.8,89.0,48.5,38.4,8.6,8.26,5.62,96.0,21.9,76.2,3,0
496,497,0,56,0,45.1,79.1,39.0,30.5,5.2,6.47,5.10,64.0,145.3,66.7,4,0
211,212,0,51,1,45.9,66.7,31.8,28.1,9.0,10.08,5.61,85.0,36.2,73.0,3,0
249,250,0,55,1,44.7,71.6,22.9,22.1,5.5,6.82,4.61,105.0,59.2,72.7,4,0
142,143,0,45,1,43.2,68.2,27.8,42.3,6.6,10.93,6.61,105.0,27.2,74.5,3,0

> Make sure you have 16 column in this test set

In [11]:
# Save the test set 
test_df.to_csv("test_summary.csv")